### ISSUE TITLE
Use AutoCloseable instead of Releasable

### ISSUE THREAD

**Issue by GrahamBorland** [eclipsesource/J2V8#102]
If you were to use `java.lang.AutoCloseable` as a direct replacement for `com.eclipsesource.v8.Releaseable`  it would allow use of try-with-resources to nicely clean up native handles. We would never need to manually call `release()` in many cases.

This:

``` java
V8Object player1 = new V8Object(runtime).add("name", "John");
V8Object player2 = new V8Object(runtime).add("name", "Chris");
V8Array players = new V8Array(runtime).push(player1).push(player2);
hockeyTeam.add("players", players);
player1.release();
player2.release();
players.release();
```

could become this:

``` java
try (
    V8Object player1 = new V8Object(runtime).add("name", "John");
    V8Object player2 = new V8Object(runtime).add("name", "Chris");
    V8Array players = new V8Array(runtime).push(player1).push(player2)) {
    hockeyTeam.add("players", players);
}
```

**Comment by mpost** [comment]
While that is true, AutoClosable is only support from Android 4.4+ so that would rule out J2V8 for a lot of Android users.

**Comment by irbull** [comment]
I looked at this when designing the 3.0 API and there were several limitations to this approach:

1. As @mpost mentioned this will not work on pre 4.4 Android devices. We also have a number of server side users using Java 1.6, and this would require us to set our minimum execution environment to 1.7.
2. AutoCloseable#close throws a checked exception. However, J2V8 release does not throw an exception, so we would require users to catch a checked Exception that could never be thrown, and not do anything with it since it doesn't exist.
3. Closeable flow analysis does not work well with a fluid API. The hockey team example from above produces 3 resource leak warnings because it cannot determine that the player[n] variable is the same object that created with _new_.
![flow](https://cloud.githubusercontent.com/assets/196883/10914838/feae6f4e-8208-11e5-89ae-ebfe562f2ee1.jpg)
This does not just affect new code, but all existing code would now produce warnings.
4. Many _try with resource_ scenarios involved short lived objects (streams, files). However, V8Objects can often be long lived, which would again produce resource leak warnings.

With all these limitations, it didn't seem worth the effort to add this.

**Comment by irbull** [comment]
I think it's time to revisit this. Some of what I said above still holds, but in the 3 years since some things have changed. I will investigate this.
