### ISSUE TITLE
NodeJs messageloop

### ISSUE THREAD

**Issue by midzelis** [eclipsesource/J2V8#160]
I haven't tried out the new 4.x stream with NodeJS yet, so take this with a grain of salt. 

I'm wondering about the performance aspects of the message loop, according to the doc and usage that I see in the src. 

    private void runMessageLoop() {
        while (nodeJS.isRunning()) {
            nodeJS.handleMessage();
        }
    }

I'm wondering if this becomes a tight spin loop, that takes up 100% of cpu. 

SWT has a similar loop for the event queue, but it has a sleep() function. If there was a nodeJS.sleep(), it could look like this: 

    private void runMessageLoop() {
        while (nodeJS.isRunning()) {
            if (!nodeJS.handleMessage()) {
                 nodeJS.sleep();
            }
        }
    }

nodeJS.sleep() would basically be Thread.sleep(), except that it returns when there is a new node JS message to handle. 

Is this needed? possible?

**Comment by irbull** [comment]
Thank-you @midzelis, I'm really happy you brought this up since I was thinking about this too. I was sitting down with the original architect of SWT earlier this year (at EclipseCon) discussing this exact topic.

The handleMessage is implemented with the following code (in C++):
```
  rt->running = uv_run(rt->uvLoop, UV_RUN_ONCE);
```
According to the [UV Docs](http://docs.libuv.org/en/v1.x/loop.html), UV_RUN_ONCE means:

> Poll for i/o once. Note that this function blocks if there are no pending callbacks. Returns zero when done (no active handles or requests left), or non-zero if more callbacks are expected (meaning you should run the event loop again sometime in the future).

So I think we should be ok. Furthermore, I changed your code snippet slightly and logged a message in the tight loop. I then ran a simple _express.js_ server. I can confirm that it does not constantly spin.

Do you think this is good enough? Do you think a sleep API would be better? Do you have ideas how that could be implemented using UV?

I don't know a lot about the node message loop and most of what I know about node.js I learned from doing this project, so any tips / trick / pointers would be greatly appreciated.

**Comment by midzelis** [comment]
Great - I'm also by no means an node.js expert, and you're talking about deep guts of node.js implementation ;-) I congratulate and praise you for taking this project on!! Thanks!!!

Looking at the docs you linked, it says that it blocks when there is nothing to run. So, thats good - it means it won't spin. I think this is good enough, especially since it doesn't seem like libuv has a sleep() equivalent, but blocking comes close. This is basically readAndDispatchThenSleep() all in one go.
