### ISSUE TITLE
Where to get version 4.1.0?

### ISSUE THREAD

**Issue by renaudpawlak** [eclipsesource/J2V8#168]
Sorry for dumb question, but how can I use version 4.1.0 for Mac OSX with Maven?
I tried here http://mvnrepository.com/artifact/com.eclipsesource.j2v8/j2v8/4.1.0 but it does not seem to work. Additionally platform-specific release seem to stop from version 4. Is that normal? Does it mean that version 4 is not OS-dependent anymore?

**Comment by alvarovn** [comment]
I have the same doubt. I am interested in j2v8_linux_x86_64 4+ since I intend to use arrow functions.

**Comment by irbull** [comment]
Sorry, I just returned from vacation.

I have had trouble building the native parts for all the other OSs (other than Android) which is why only android builds are available for 4.1.0. 

Now for the good news. I have recent release builds ready for Win32, Win64, MacOS, and Linux64 ready. I will be pushing these out with a service release 4.2.1 today. I will update this issue when the builds hit Maven Central. Sorry about the wait.

**Comment by irbull** [comment]
I had a few problems releasing and a few new APIs I added, so in the end the version is 4.3.0. It should be available with the following pom dependency:
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8_linux_x86_64</artifactId>
  <version>4.3.0</version>
</dependency>
```

**Comment by alvarovn** [comment]
Thank you!
