### ISSUE TITLE
Passing double[] to V8Object.executeVoidFunction via V8Array

### ISSUE THREAD

**Issue by activetheory** [eclipsesource/J2V8#179]
Hi,

Trying to implement a callback where I pass the values of a `double[]` to an executeVoidFunction call but I can't see a way to pass it in to V8Array parameters. Is there a way to accomplish this?

This leads to a follow up question/feature request which is I will be attempting to create the functionality of [transferable objects](https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast?hl=en). 

Essentially, I will pass a Float32Array to Java from a WebWorker to be passed back to the main V8 thread via a callback. Is there a way to pass a `double[]` from `array.getDoubles()` into a callback as described in my first question?

**Comment by irbull** [comment]
No, right now only V8Objects / V8Arrays can be passed (or primitive Java objects). In this case you would need to create V8Array and push the doubles you want. 

Another option with J2V8 4 is to use TypedArrays and get the underlying `java.nio.ByteBuffer` as a `DoubleBuffer` and add the values there. While we could add a convince API that would allow `double[]` and `int[]` to be passed to `executeFunction` this would copy the values under the covers because V8 doesn't know this structure.

**Comment by activetheory** [comment]
Thanks for the response! The `TypedArrays` option looks promising. Could you point me to a code snippet or test that would illustrate how to pass the filled `DoubleBuffer` back to JavaScript?

**Comment by irbull** [comment]
Here is an example of how you can use `DoubleBuffer` and write floating point numbers directly to it. Note, I also use `executeJSFunction` which is new in 4.4 and is _slightly_ different than `executeFunction`. Instead of passing a `V8Array` you just pass the parameters you want to a vararg and the `V8Array` gets created for you. 

```
		V8 v8 = V8.createV8Runtime();
		V8ArrayBuffer buffer = new V8ArrayBuffer(v8, 8 * 10);
		V8TypedArray typedArray = new V8TypedArray(v8, buffer, V8Value.FLOAT_64_ARRAY, 0, 10);
		
		v8.executeVoidScript("\n"
				+ "function foo( d ) {\n"
				+ " return d.reduce( ( i, result ) => result + i);\n"
				+ "}\n");
				
		DoubleBuffer doubleBuffer = buffer.getBackingStore().asDoubleBuffer();
		
		for ( int i = 0; i < 10; i++) {
			doubleBuffer.put((double)i);
		}
		
		System.out.println(v8.executeJSFunction("foo", typedArray));
		
		buffer.release();
		typedArray.release();
		v8.release();
```
