### ISSUE TITLE
How can I get an Java-Object?

### ISSUE THREAD

**Issue by fifiand1** [eclipsesource/J2V8#198]
I create an Java-Object(cn.xxx.Element) like

`var node=document.createElement("label")`

then I set some attributes

`node.setAttribute("value","222")`

Everythis is fine...
But I want to add the node to a body node like

`document.getElementById("body").appendChild(node)`

there is an exception:

`undefined:3: com.eclipsesource.v8.V8Object cannot be cast to cn.xxx.Element`

the version I using is 3.0.2.Sorry if this is documented somewhere and I missed it.

**Comment by Haringat** [comment]
That is a strange error. Since the position it occurs at is in javascript it should not be complaining about java casting errors. Are you sure that this is the position that produces that error?

**Comment by Haringat** [comment]
I just realized that I got something wrong about how your structure is.
So as far as I understand you now, what you want is having a possibility to get a V8 equivalent of just about any object by a simple function call and the original Java object back the same way. I can tell you: J2V8 does not (and to be fair: can not) support this because Java does not support "duck typing" as JavaScript does. You cannot just let an object pop out of nowhere. You have to get objects by calling constructors and since there is no convention about how constructors have to look J2V8 can not possibly know how to create that cn.xxx.Element object you want to have. What you can do is the following:
You could use com.eclipsesource.v8.utils.V8ObjectUtils.toMap() to get a Map equivalent of the Javascript object which could allow you (depending on your code) to retrieve access to the original object or (if the object for now only existed inside JavaScript) create a new one.

**Comment by fifiand1** [comment]
Thank you for the answer. I will try another way.
