### ISSUE TITLE
Can I use multiple js files like in Node.js?

### ISSUE THREAD

**Issue by mattxia** [eclipsesource/J2V8#213]
My JS project is composed of several js files like in Node, how can I run them in J2V8? thanks.

**Comment by Haringat** [comment]
Well, you could write a rudimentary require() function with J2V8's .runScript() method as a proxy to access them.
I think that J2V8 currently doesn't support loading of external files, which makes sense since the only standardized method of script loading would be ES6 Modules and for those the V8 support is needed first. So that's not really a J2V8 problem but rather a V8 problem. I can recall having seen an incomplete implementation of that in a former V8 build but I can't find it on my current node.js version so I guess they removed it for now.

**Comment by irbull** [comment]
There is also a `require()` method on the NodeJS, but I'm not sure it will work exactly like node.js require because of how messages are processed. But give that a try @mattxia and see if it works for you.
