### ISSUE TITLE
functionRegistry holding on to callbacks even after original V8Function released

### ISSUE THREAD

**Issue by artcodex** [eclipsesource/J2V8#242]
Hi,

I noticed in an app I have that the memory grows continually because I have callbacks that hold onto certain objects, and even though I release all the V8Function objects I've created for those callbacks once I'm done the callbacks are still alive in the functionRegistry hashmap in the V8 engine class I'm using. 

Basically I create the engine once for my app and then run a scenario, but I want the memory used and these callbacks to disappear after each scenario run. It seems these callbacks should be removed from the functionRegistry once I am done with the V8Function object and have released it.

**Comment by irbull** [comment]
The problem is that even though you have released it, V8 (i.e. JavaScript) could still require it. Consider the following example:
```
     public void testCallback() {
        V8Function v8Function = new V8Function(v8, new JavaCallback() {

            @Override
            public Object invoke(final V8Object receiver, final V8Array parameters) {
                System.out.println("Hi, from Java");
                return null;
            }
        });
        v8.add("globalFunction", v8Function);
        v8Function.release();
        v8.executeScript("globalFunction()");
    }
```
Here we release the `v8Function`, but at some later date `globalFunction()` is called, and this is expected to call the body from `v8Function`.

We have attempted to address this by adding a `WeakCallbackInfo` in C++. This should be called when the JS method is no longer in scope or otherwise removed from JS. You can see this here https://github.com/eclipsesource/J2V8/blob/master/jni/com_eclipsesource_v8_V8Impl.cpp#L1629
