### ISSUE TITLE
Call to V8.release(boolean) does not shut down the engine

### ISSUE THREAD

**Issue by mpost** [eclipsesource/J2V8#29]
When calling <code>V8.release(boolean)</code> i would expect to shut down the engine completely. Instead the entire internal state is preserved and the engine can be used as before.

A dedicated "dispose" method that frees operating system resources should be available.

**Comment by irbull** [comment]
There should be no internal state after release is called. The native side memory is disposed during release and if any JNI code is accessed it will fail in very unpredictable ways. To ensure this is the case, we now check if the runtime is disposed during the thread check. Fixed with commit d588d5e479d494f0b71798e0fffef2bdfc80490e.
