### ISSUE TITLE
Approaches to running Node on Android

### ISSUE THREAD

**Issue by aschrijver** [eclipsesource/J2V8#326]
Hi,

This is just a FYI, feel free to close.

I am not familiar to the native linking, compiling techniques in bringing Node to android, so find it hard to choose between options. To not waste your time, I first created a SO question with some of the approaches I found.

Here is the link: [Approaches to running NodeJS on Android](https://stackoverflow.com/q/45459909/8295283)

**Comment by aschrijver** [comment]
I have created a detailed answer to my earlier SO question, with J2V8 evaluation in it:

- [Viable options to running NodeJS on Android (Aug 2017)](https://stackoverflow.com/a/45649995/8295283)

**Comment by irbull** [comment]
I wasn't able to build J2V8 with Node support for Android. I do think that's interesting, but it's out of scope. In order to move this project forward, we must reduce the scope. Please see #441.

If someone is able to use J2V8 for that, then I would be happy to link to them and somehow integrate that as a downstream project.
