### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by irbull** [eclipsesource/J2V8#342]
With the isolate fixes and the new build system, we should cut a new J2V8 release. Some questions:

1. What version of node / v8 should we use
2. What platforms should we release for (I have access to appveyor for windows builds)
3. What version should J2V8 be.

cc: @matiwinnetou @drywolf

**Comment by muthu90ec** [comment]
It would be great if we get J2v8 for Windows, Mac and Linux released into the mavencentral repo

**Comment by matiwinnetou** [comment]
My suggestion is that we should for the moment keep NodeJS 7.4.0, it is proven to work. Next release could include an upgrade. Needless to say I would like an upgrade but first things first, stability comes first and this release contains important fixes.

We should release for:
1. linux 64
2. osx 64
3. windows
4. android 32/64?

alpine is a bit exotic and I would let individuals release themselves unless this is really easy

I suggest 4.9.0 version

**Comment by irbull** [comment]
I need android x86 and android arm (and in a single aar file). I opened #341 for that -- since those paying me to work on this require that, I need to make sure that's available ;). Beyond that, I like the list you have. I'll try the windows builds today.

**Comment by Kernle32DLL** [comment]
@irbull Is there anything I can do to provide support to make alpine builds come true? With the new build system having the capability and all...

**Comment by matiwinnetou** [comment]
@Kernle32DLL it is supported due to amazing work from @drywolf, the point is about pushing to maven central releases. You have to agree that alpine while amazing in some ways distro is still in a corner in terms of typical companies running apps in data centers... If one would push alpine why not push all other "linux" vendors with various incompatible glibc incarnations. This would increase already probably long release time (imagine to build all those libraries will take a lot of time by travis build). Just my 2 cents.

**Comment by sherrybomb** [comment]
Is there an idea of a timeframe for this release? I'm eagerly awaiting fixes for a couple issues ([#303](https://github.com/eclipsesource/J2V8/pull/303), [#188](https://github.com/eclipsesource/J2V8/issues/188)).

**Comment by djx314** [comment]
+1 for timeframe for this release.

**Comment by Kernle32DLL** [comment]
@matiwinnetou I disagree in Alpine being a "corner". At least in the containerization context, Alpine flavored releases are distributed for all pretty much all major projects (take a look at the [Alpine package manager](https://pkgs.alpinelinux.org/packages)).

Also, Oracle recently started to [roll out their own Docker images](https://store.docker.com/images/oracle-serverjre-8), with [a JDK 9 Alpine version being in the pipeline](http://jdk.java.net/9/ea). OpenJDK has offered [Alpine images](https://hub.docker.com/_/openjdk/) since Java 7.

So, I would not recommend to brush this topic off so easily.

**Comment by djx314** [comment]
@irbull How about the status of this issue?

**Comment by matiwinnetou** [comment]
@djx314 I think that @irbull officially vanished or he is so busy that cannot find time to work on this project anymore :(

**Comment by irbull** [comment]
We now have 64 bit support and a reproducible build job that can build, sign and push to maven central.

In gradle:
`implementation 'com.eclipsesource.j2v8:j2v8:5.0.103@aar'`
`implementation 'com.eclipsesource.j2v8:j2v8:4.8.4@aar'`

or in a maven pom

```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>4.8.4</version>
  <type>aar</type>
</dependency>
```
or
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>5.0.103</version>
  <type>aar</type>
</dependency>
```

All those builds contain the binaries for x86, x86_64, arm and arm64. If you call
`v8.getSCMRevision();` in your application, you'll see the commit hash that the artifact was built against. For 4.8.4 it's 8a79c8b and for 5.0.103 it's e6ac51a.
