### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by lsmobile** [eclipsesource/J2V8#367]
Hello, connoisseurs!

When I try to execute the `build -t win32 -a x64 -ne` command, the system gives an error:
```
>build -t win32 -a x64 -ne
Checking Node.js builtins integration consistency...
ERROR: J2V8 linking builtins code does not match Node.js builtin modules, check jni/com_eclipsesource_v8_V8Impl.cpp
        J2V8 definition is missing node-modules: ['inspector', 'http2', 'performance', 'serdes']
```
What can be done? Thank you in advance!

**Comment by mhsjlw** [comment]
Having the same issue

**Comment by irbull** [comment]
In order to help move J2V8 forward, we are reducing the scope and focusing only on Android. Others are free to build/maintain other platforms, but I, unfortunately, don't have the cycles (and I don't even have a windows machine to test on). I think it's better to be honest about the state of the project than to just let these bugs sit here. Please see #441 for more information.

If someone would like to support Windows, please let me know.
