### ISSUE TITLE
Why J2V8 requires Java7?

### ISSUE THREAD

**Issue by angelozerr** [eclipsesource/J2V8#38]
It seems that J2V8 is build with Java 1.7.0_71. Why?

Do you think it's possible to provide a JAR which requires Java 6? Or perhaps Java 5 is enough?

**Comment by irbull** [comment]
Probably because that's the version of Java I had when I started developing J2V8 ;). Since the J2V8 core uses nothing but arrays, it can likely even target pre 1.5 VMs. There are some utilities that convert V8 Objects to Maps and Lists -- and those uses generics in a few places. 

The only concern I would have is related to JNI and has the JNI API changed at all since Java 5 or Java 6.

**Comment by angelozerr** [comment]
If you target to Java 6, it should be very cool.

**Comment by irbull** [comment]
Fixed with 5f52f048ac64b764dc3dbdff1f55aada06b6d4e4.
