### ISSUE TITLE
Official build containing 64-bit Android binaries

### ISSUE THREAD

**Issue by JessHolle** [eclipsesource/J2V8#453]
While the build supposedly supports 64-bit binaries now, it would be best to have an official release and build rather than everyone having to build their own at various point in time snapshots of HEAD.

**Comment by GrahamBorland** [comment]
FWIW I [pinged @irbull on Twitter](https://twitter.com/gborland/status/1105440276129218560) in the hope of eliciting some kind of response. I feel a bit bad about stalking him over there, but I'm getting really concerned about the silence here on GH.

**Comment by irbull** [comment]
We now have official, signed, builds of J2V8 for both the 5.x and the 4.8 streams. Both of these have been pushed to maven central.

In gradle:
`implementation 'com.eclipsesource.j2v8:j2v8:5.0.103@aar'`
`implementation 'com.eclipsesource.j2v8:j2v8:4.8.4@aar'`

or in a maven pom
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>4.8.4</version>
  <type>aar</type>
</dependency>
```
or
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>5.0.103</version>
  <type>aar</type>
</dependency>
```
All those builds contain the binaries for x86, x86_64, arm and arm64. If you call
`v8.getSCMRevision();` in your application, you'll see the commit hash that the artifact was built against. For 4.8.4 it's `8a79c8bea8274c2334271a638eca601ffe82f01f` and for 5.0.103 it's `e6ac51aad2902ea401a752a35cb9f148be35808d`.

Thanks, everyone for all your patience. Thanks, @JessHolle for sticking with this and the tips for the armv8 stuff (I included a fix for that). Sorry, @GrahamBorland, I just saw your message on twitter today, I've been trying to avoid social media -- not because of J2V8, just in general. 

Let me if they work, don't work, or you see any problems.
