### ISSUE TITLE
[3.0] Suppport locker for multi thread.

### ISSUE THREAD

**Issue by angelozerr** [eclipsesource/J2V8#46]
Instead of checking that all interactions come from the same thread J2V8 should create a locker, and
then we'll check that all interactions come from the thread with the locker. 

The locker can be acquired and released. With this approach you can release the locker after you create the JavaScript variable, and then acquire it in the new thread before you use it.

**Comment by irbull** [comment]
Fixed with 6f61bf7290644b94e14d2dd96b61abe50b3de26b. You can now call v8.getLocker().release(); to release the thread from the runtime. Another thread can call v8.getLocker().acquire() to get control. When a runtime is first created, the thread that created it is given the lock.

I'll push this to the snapshop repository early next week as it's a long weekend here in Canada.

**Comment by irbull** [comment]
Pushed to the snapshot repository.
