### ISSUE TITLE
Which version of j2v8 supports NodeJs running in android applications

### ISSUE THREAD

**Issue by lijiananll** [eclipsesource/J2V8#460]
I want to run NodeJs on android Which version of j2v8 will support NodeJs running in android applications

**Comment by irbull** [comment]
In order to keep this project going, we had to set a focus and reduce the scope. See #441 for details. In short, we don't have official builds that support J2V8 with Node on Android. The code is here, and you are free to make that work or take that on, but I won't be able to support that work. I'm sorry, but I just don't have the time.
