### ISSUE TITLE
Getting the latest V8 j2v8 lib

### ISSUE THREAD

**Issue by Vrganj** [eclipsesource/J2V8#496]
Hey, I've been trying to update the V8 used in J2V8. I'm wondering how did you get the dll for Windows x64?

**Comment by ahmadov** [comment]
Hi, @Vrganj 
the current version (6.0.0) of the J2V8 uses the V8 version 7.4.288 but it is only available for Android. Because of #441 we decided to reduce the scope of the project. 
So, the latest version of the J2V8 is not available for Windows platform right now.
Please refer the #477 and #479 as a starting point what we did to upgrade the V8 version used in the J2V8.

**Comment by Vrganj** [comment]
I'm not asking you to make any changes to the repository and I'm not asking you if the latest version if available for Windows. I'm just asking how you got the .dll for Windows? I'm going to try getting it myself.
