### ISSUE TITLE
Clunky twin behavior

### ISSUE THREAD

**Issue by djMax** [eclipsesource/J2V8#57]
Right now, when you twin() something, e.g. a V8Function, you get a V8Value back, making you cast it back to v8function and feel all gross inside. Could this be a generic function of some sort? Or some other way to pretty it up?

Secondly, pushing null requires a disambiguation cast right now, perhaps a pushNull() method like pushUndefined()?

**Comment by irbull** [comment]
We can overide by covariant return type, so in V8Function we can override
twin and return V8Function (and to the cast there). This would be cleaner.

pushNull seems reasonable too. The first one in more important right now
since I'm trying to lock down API. Adding new API is easier to do later,
but I don't want to change much API after we declare 3.0.

On Thu, May 21, 2015 at 12:12 PM, Max Metral <notifications@github.com>
wrote:

> Right now, when you twin() something, e.g. a V8Function, you get a V8Value
> back, making you cast it back to v8function and feel all gross inside.
> Could this be a generic function of some sort? Or some other way to pretty
> it up?
>
> Secondly, pushing null requires a disambiguation cast right now, perhaps a
> pushNull() method like pushUndefined()?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/57>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by irbull** [comment]
Let's use this to track the work on twin(). I've filed issue #60 for the pushNull / addNull support.

**Comment by irbull** [comment]
Fixed with ef1a76cba418aac127cb600fe1b4c445fa0173d4.
