### ISSUE TITLE
Debugging support?

### ISSUE THREAD

**Issue by jason-parkhurst** [eclipsesource/J2V8#82]
I can't seem to get the debugging support in version 3.0 to work.  The eclipse plugin says it is initializing and never finishes.  

Also, when I pass true for it to wait for the debugger to connect it just keeps going.  I noticed the calls are deprecated but had hoped it still worked....

Any help?  We'd really like to use this for a project but without debugging support it's a hard sell.

**Comment by irbull** [comment]
What are you trying to debug? And android device or J2V8 running on your own system? If you are trying to debug a remote device, V8 does not allow this. You must run Eclipse from the same device that you are trying to debug on.

However, because this is not practical, we have built a [Debug Tunnel](https://github.com/eclipsesource/J2V8/blob/master/src/main/java/com/eclipsesource/v8/utils/DebugTunnel.java) which will create a proxy on your device and forward all requests through the proxy to V8. This way you can remotely debug your J2V8 apps. 

Can you post the code you are using to setup the debugger.

As for why the methods are deprecated... this is because V8 no longer supports debugging (new versions of V8). Once we move to that, we will need to find another way to support debugging.

**Comment by jason-parkhurst** [comment]
I'm running it on a mac.  Here's the code:
```
import com.eclipsesource.v8.V8;

public class Test {
    public static void main(String[] args) {
        new Test().go();
    }

    public void go() {
        V8 v8 = V8.createV8Runtime();
        v8.enableDebugSupport(9928, true);
        v8.registerJavaMethod(this, "println", "println", new Class<?>[]{String.class});
        v8.executeVoidScript("while(true) { println('go'); }");
        v8.release();
    }

    public void println(String s) {
        System.out.println(s);
    }
}
```

It immediately starts printing go, and doesn't wait for the debugger to attach.
Even though it didn't wait, for this example I can attach later from the debugger in Eclipse.

I'm afraid I don't have a small example of it failing to attach at all;  it seems to depend on what the code is doing at the time....  I've worked around it in our codebase, though, so we're going to move forward.  Thanks for putting this out there.

**Comment by irbull** [comment]
I can't remember the details of the V8 debug protocol, but it was working before and nothing has changed recently. I think you may need to enable debug support, then connect from the Debgger, then execute your script.

Furthermore, in your example you enter into an infinite loop in JS, giving V8 no chance to handle the debug messages. You will need to `registerDebugHandler(final Runnable handler)`, and in the runnable call `processDebugMessages(final V8 runtime)`.

**Comment by LorelaiL** [comment]
I can reproduce this on 3.0.1, runtime.enableDebugSupport(1100,true); doesn't wait for connection. 
On 2.2.1 it waits for debugger connection.
In example above it is expected to wait for connection before any JavaScript is executed.

**Comment by irbull** [comment]
A new Debug API is now in master and the old Debug agent is removed (since it's no longer in V8). I will write some articles on how to use this API.

**Comment by thenilly** [comment]
Are there any articles on how to use the debug API, especially when running code on an Android device? Thanks.

**Comment by AlexTrotsenko** [comment]
@thenilly  it might too late for you, but if it is still relevant - check #414
