### ISSUE TITLE
v8ObjectInstanceCounter rolls over

### ISSUE THREAD

**Issue by jason-parkhurst** [eclipsesource/J2V8#99]
If you make enough V8Values over time, even if you release them all, eventually the v8ObjectInstanceCounter rolls over and negative handles are assigned.  Among other things, this causes calls to functions to receive no arguments since the code checks for a non-negative handle to the parameters array.  

Can you realistically use 2 billion handles?  Yes;  running our server app using J2V8 hard ends up making that many calls in the course of 3 days or so.

**Comment by irbull** [comment]
Thanks for this report.

I switched the way V8Instances are tracked by using their physical memory address as opposed to a counter. I will do the same with V8Values to avoid the counter.

**Comment by irbull** [comment]
I've investigated this.Instead of using an object counter, I am now using the memory address (as a long) of the V8Object. This won't roll over until you run out of memory ;). This will be a pretty big change as it modifies how all the V8Objects are looked up in the native code, but it's the right approach and truly make J2V8 a 64 bit platform. 

I will complete this work next week.

**Comment by irbull** [comment]
I've managed to create & release over 6 billion V8Objects with this change. I'll fix up the change-set and commit it tomorrow.

**Comment by irbull** [comment]
Fixed with 731f57d98d544b0501bf1f5e3ccfd9ab98a23ce4
